version: "3.9"
services:
  client:
    build: ./client
    networks:
      - merkle-net

  server:
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - merkle-net

networks:
  merkle-net:

