version: "3.9"
services:
  server1:
    build: 
      context: .
      dockerfile: server/Dockerfile
    environment:
      - SERVER_PORT=5001
    ports:
      - "5001:5001"
    networks:
      - merkle-net
    depends_on:
      - db

  server2:
    build: 
      context: .
      dockerfile: server/Dockerfile
    environment:
      - SERVER_PORT=5002
    ports:
      - "5002:5002"
    networks:
      - merkle-net
    depends_on:
      - db

  upload-client:
    build:
      context : .
      dockerfile: client/Dockerfile
    volumes:
      - ./demo:/app/demo
    networks:
      - merkle-net
    entrypoint: ["/client", "-operation=upload", "-filePaths=/app/demo/file1.txt,/app/demo/file2.txt,/app/demo/file3.txt,/app/demo/file4.txt"]
    depends_on:
      - server1
      - server2
      - client-db

  download-client:
    build:
      context : .
      dockerfile: client/Dockerfile
    networks:
      - merkle-net
    entrypoint: ["/client", "-operation=download", "-filePaths=/app/demo/file1.txt"]
    depends_on:
      - upload-client
      - client-db

  db:
    image: postgres:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      "POSTGRES_DB": "mydb"
      "POSTGRES_USER": "user"
      "POSTGRES_PASSWORD": "password"
    networks:
      - merkle-net

  client-db:
    image: postgres:latest
    volumes:
      - ./init-client.sql:/docker-entrypoint-initdb.d/init-client.sql
    ports:
      - "5433:5432"
    environment:
      "POSTGRES_DB": "clientdb"
      "POSTGRES_USER": "clientuser"
      "POSTGRES_PASSWORD": "clientpassword"
    networks:
      - merkle-net

networks:
  merkle-net:
    driver: bridge
